baseURL = "https://yourcustomdomain.com/"
title = "Tech4Village"
theme = "PaperMod"
languageCode = "en-us"

[params]
  author = "Kaggwa Karenge"
  description = "Bridging the digital divide in rural Kenya."
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowWordCount = true
  ShowToc = true
  defaultTheme = "auto"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1
[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 2
[[menu.main]]
  name = "Project"
  url = "/project/"
  weight = 3
[[menu.main]]
  name = "Get Involved"
  url = "/involved/"
  weight = 4
[[menu.main]]
  name = "Blog"
  url = "/blog/"
  weight = 5
[[menu.main]]
  name = "Donate"
  url = "/donate/"
  weight = 6
[[menu.main]]
  name = "Contact"
  url = "/contact/"
  weight = 7 